export const WIDGET_ICON_CATALOG = Object.freeze([
  ["message-circle", "Message", "Communication"],
  ["messages-square", "Messages", "Communication"],
  ["message-square-text", "Message text", "Communication"],
  ["bot", "Bot", "People"],
  ["brain", "Brain", "People"],
  ["headset", "Headset", "Communication"],
  ["phone", "Phone", "Calls"],
  ["phone-call", "Phone call", "Calls"],
  ["phone-off", "End call", "Calls"],
  ["mic", "Microphone", "Calls"],
  ["mic-off", "Microphone off", "Calls"],
  ["volume-2", "Speaker", "Calls"],
  ["volume-x", "Speaker off", "Calls"],
  ["play", "Play", "Actions"],
  ["pause", "Pause", "Actions"],
  ["loader-circle", "Spinner", "Actions"],
  ["x", "Close", "Actions"],
  ["home", "Home", "Actions"],
  ["chevron-left", "Back", "Actions"],
  ["send", "Send", "Actions"],
  ["paperclip", "Attachment", "Files"],
  ["download", "Download", "Files"],
  ["smile", "Emoji", "Communication"],
  ["image", "Image", "Files"],
  ["camera", "Camera", "Files"],
  ["file", "File", "Files"],
  ["file-text", "Document", "Files"],
  ["file-spreadsheet", "Spreadsheet", "Files"],
  ["file-archive", "Archive", "Files"],
  ["user", "User", "People"],
  ["users", "Users", "People"],
  ["user-round-check", "Verified user", "People"],
  ["sparkles", "Sparkles", "Brand"],
  ["life-buoy", "Support", "Brand"],
  ["help-circle", "Help", "Brand"],
  ["info", "Information", "Brand"],
  ["bell", "Bell", "Brand"],
  ["calendar", "Calendar", "Business"],
  ["mail", "Email", "Communication"],
  ["globe", "Globe", "Business"],
  ["zap", "Lightning", "Brand"],
  ["shield-check", "Shield", "Business"],
  ["shopping-cart", "Cart", "Commerce"],
  ["package", "Package", "Commerce"],
  ["credit-card", "Payment", "Commerce"],
  ["wrench", "Tools", "Business"],
  ["settings", "Settings", "Business"],
  ["search", "Search", "Actions"],
  ["map-pin", "Location", "Business"],
  ["heart", "Heart", "Brand"],
  ["star", "Star", "Brand"],
  ["check", "Check", "Actions"],
  ["check-circle", "Success", "Actions"],
  ["arrow-right", "Arrow", "Actions"],
  ["external-link", "External link", "Actions"],
]);

export const WIDGET_ICON_IDS = Object.freeze(WIDGET_ICON_CATALOG.map(([id]) => id));

export function normalizeWidgetIconId(value, fallback = "message-circle") {
  const aliases = {
    message: "message-circle",
    chat: "messages-square",
  };
  const candidate = aliases[value] || value;
  return WIDGET_ICON_IDS.includes(candidate) ? candidate : fallback;
}
